### ISSUE TITLE
'Empty input file' error

### ISSUE THREAD

**Issue by harry-wood** [jywarren/mapmill#8]
On mapmill.org this error crops up every now again. I guess 'Empty input file' is a problem.

MiniMagick::Error in MapperController#index

Command ("identify -ping /tmp/mini_magick20121105-15328-1ga1ogj-0.JPG") failed: {:output=>"identify: Empty input file `/tmp/mini_magick20121105-15328-1ga1ogj-0.JPG' @ error/jpeg.c/EmitMessage/233.\n", :status_code=>1}
RAILS_ROOT: /media/earth/sites/mapmill.org

Application Trace | Framework Trace | Full Trace
/media/earth/sites/mapmill.org/vendor/gems/mini_magick-3.2.1/lib/mini_magick.rb:392:in `run'
/media/earth/sites/mapmill.org/vendor/gems/mini_magick-3.2.1/lib/mini_magick.rb:374:in `run_command'
/media/earth/sites/mapmill.org/vendor/gems/mini_magick-3.2.1/lib/mini_magick.rb:178:in `valid?'
/media/earth/sites/mapmill.org/vendor/gems/mini_magick-3.2.1/lib/mini_magick.rb:143:in `create'
/media/earth/sites/mapmill.org/vendor/gems/mini_magick-3.2.1/lib/mini_magick.rb:53:in `read'
/media/earth/sites/mapmill.org/vendor/gems/mini_magick-3.2.1/lib/mini_magick.rb:114:in `open'
/media/earth/sites/mapmill.org/vendor/gems/mini_magick-3.2.1/lib/mini_magick.rb:113:in `open'
/media/earth/sites/mapmill.org/app/models/image.rb:40:in `thumb'
/media/earth/sites/mapmill.org/app/controllers/mapper_controller.rb:36:in `index'

**Comment by jywarren** [comment]
closing due to MapMill 2: https://github.com/publiclab/mapmill
